variables:
  REVISION: "0"
  VERSION: "${CI_COMMIT_TAG}-${REVISION}"
  PACKAGE_REGISTRY_URL: "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/chromium-ppc64le-patches-quilt/${VERSION}"

before_script:
  - apt-get update -yq
  - DEBIAN_FRONTEND="noninteractive" apt-get install -y make quilt wget

stages:
  - build
  - upload
  - release

default:
  image: ubuntu:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive

build:
  stage: build

  only:
    - tags

  tags:
    - docker

  script:
    - make dist

  artifacts:
    paths:
      - target/patches-*.tar.gz

upload:
  stage: upload

  only:
    - tags

  tags:
    - ppc64le
    - docker

  script:
    - chmod +x ./upload.sh
    - ./upload.sh

release:
  stage: release

  tags:
    - ppc64le
    - docker

  only:
    - tags

  script:
    - chmod +x ./release.sh
    - ./release.sh
