# Copyright 2019 Colin Samples
#
# SPDX-License-Identifier: Apache-2.0
#

prefix ?= /usr/local

bindir = $(prefix)/bin

.PHONY: install
install:
	install -d $(bindir)
	install -t $(bindir) git-format-patch-chrome

